version: "3.8"

services:
  jenkins:
    image: docker.io/jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--prefix=/
    volumes:
      - jenkins_home:/var/jenkins_home
      # - /run/podman/podman.sock:/var/run/docker.sock:rw
      # (optional) mount Jenkinsfile project root for testing
      - ../api:/workspace/api:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  jenkins_home: